export const UPDATE_CONVERSATIONS = 'UPDATE_CONVERSATIONS';
export const CONVERSATIONS_REQUESTED = 'CONVERSATIONS_REQUESTED';
export const CONVERSATIONS_UPDATED = 'CONVERSATIONS_UPDATED';

export const RECEIVED_CONVERSATIONS = 'RECEIVED_CONVERSATIONS';