export const UPDATE_GLOBAL_APP_PROPERTIES = 'UPDATE_GLOBAL_APP_PROPERTIES';
export const GLOBAL_APP_PROPERTIES_REQUESTED = 'GLOBAL_APP_PROPERTIES_REQUESTED';
export const GLOBAL_APP_PROPERTIES_UPDATED = 'GLOBAL_APP_PROPERTIES_UPDATED';

export const ACTIVATE_MANUAL_LOCATION_EDIT_MODE = 'ACTIVATE_MANUAL_LOCATION_EDIT_MODE';
export const SUBMIT_MANUALLY_ENTERED_ZIPCODE = 'SUBMIT_MANUALLY_ENTERED_ZIPCODE';
export const SUBMIT_UPDATED_LOCATION = 'SUBMIT_UPDATED_LOCATION';
