export const UPDATE_GLOBAL_APP_PROPERTIES = 'UPDATE_GLOBAL_APP_PROPERTIES';
export const GLOBAL_APP_PROPERTIES_REQUESTED = 'GLOBAL_APP_PROPERTIES_REQUESTED';
export const GLOBAL_APP_PROPERTIES_UPDATED = 'GLOBAL_APP_PROPERTIES_UPDATED';

export const UPDATING_MANUALLY_EDITING_ZIPCODE = 'UPDATING_MANUALLY_EDITING_ZIPCODE';
