export const UPDATE_LISTINGS = 'UPDATE_LISTINGS';
export const LISTINGS_REQUESTED = 'LISTINGS_REQUESTED';
export const LISTINGS_UPDATED = 'LISTINGS_UPDATED';
export const UPDATED_LISTINGS_RECEIVED = 'UPDATED_LISTINGS_RECEIVED';
