export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_SUCCESS_PROCESSED = 'LOGIN_SUCCESS_PROCESSED';
export const LOGOUT = 'LOGOUT';

export const AUTH0_LOGIN_SUCCESS = 'AUTH0_LOGIN_SUCCESS';