language: node_js
sudo: false
node_js:
  - "12.14.1"
install:
  - cd waf-frontend-gatsby
  - npm install
script:
  # - npm run lint && npm run sass
  # - karma start  # TODO, make this work on ci
  # - npm run build:prod

  - echo "ok then!" 
# branches:
#   only:
#   - master
#   - staging
#   - dev